# Generated by Django 5.0.6 on 2024-05-21 19:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Products', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='items',
            name='make',
            field=models.ForeignKey(default=' ', on_delete=django.db.models.deletion.DO_NOTHING, to='Products.itemsmake'),
        ),
        migrations.AlterField(
            model_name='items',
            name='price',
            field=models.IntegerField(),
        ),
    ]
