# Generated by Django 5.0.6 on 2024-05-21 19:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Products', '0002_alter_items_make_alter_items_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='items',
            name='image',
            field=models.ImageField(blank=True, default='not_available.png', null=True, upload_to='product_images/'),
        ),
    ]
